import os


DATA_FOLDER = 'incidents_cleaned'
DATA_TRAIN_FOLDER = 'train'
DATA_VALIDATE_FOLDER = 'val'
DATA_TEST_FOLDER = 'test'
DATA_TEST_FOLDER_TEMP = 'test_temp'

CURRENT_DIR = os.getcwd()
DATA_DIR = os.path.join(CURRENT_DIR, DATA_FOLDER)

DATA_TRAIN_DIR = os.path.join(DATA_DIR, DATA_TRAIN_FOLDER)
DATA_VALIDATE_DIR = os.path.join(DATA_DIR, DATA_VALIDATE_FOLDER)
DATA_TEST_DIR = os.path.join(DATA_DIR, DATA_TEST_FOLDER)
DATA_TEST__TEMP_DIR = os.path.join(DATA_DIR, DATA_TEST_FOLDER_TEMP)

NUM_COLORS = 3
IMG_HEIGHT = 224
IMG_WIDTH = 224

BATCH_SIZE = 5

NUM_CLASS = 8

EPOCHS = 2